import { TextTemplate, TemplateCategory } from "../types";

export const BUILTIN_CANVAS_TEMPLATES: TextTemplate[] = [
  {
    id: "split-reveal",
    label: "Split Reveal Lower Third",
    category: "lower-third",
    duration: 3,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "bg-bar",
        shape: "rect",
        fill: "rgba(30, 30, 40, 0.85)",
        stroke: { color: "#7c6fff", width: 2 },
        x: 100,
        y: 850,
        width: 450,
        height: 120,
        animation: {
          in: "slide-up",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "primary-name",
        content: "Alex Rivers",
        fontFamily: "Poppins",
        fontSize: 36,
        fontWeight: 400,
        color: "#ffffff",
        align: "left",
        x: 130,
        y: 865,
        width: 390,
        height: 45,
        role: "primary",
        animation: {
          in: "slide-right",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "secondary-title",
        content: "Creative Director",
        fontFamily: "Poppins",
        fontSize: 24,
        fontWeight: 400,
        color: "#9A9AAA",
        align: "left",
        x: 130,
        y: 915,
        width: 390,
        height: 35,
        role: "secondary",
        animation: {
          in: "slide-right",
          out: "fade",
          inDuration: 0.7,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "modern-opener",
    label: "Modern Title Opener",
    category: "title-card",
    duration: 4,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "block-bg",
        shape: "rect",
        fill: "#7c6fff",
        x: 460,
        y: 400,
        width: 1000,
        height: 280,
        animation: {
          in: "scale-in",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.4,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "title-text",
        content: "EXPLORE MORE",
        fontFamily: "Poppins",
        fontSize: 84,
        fontWeight: 400,
        color: "#ffffff",
        align: "center",
        x: 460,
        y: 440,
        width: 1000,
        height: 100,
        role: "primary",
        animation: {
          in: "slide-down",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "subtitle-text",
        content: "A Cinematic Experience",
        fontFamily: "Poppins",
        fontSize: 32,
        fontWeight: 400,
        color: "#a49bff",
        align: "center",
        x: 460,
        y: 560,
        width: 1000,
        height: 50,
        role: "secondary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.8,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "clean-caption",
    label: "Clean Caption Bar",
    category: "caption",
    duration: 3,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "caption-bg",
        shape: "rect",
        fill: "rgba(0, 0, 0, 0.7)",
        x: 460,
        y: 920,
        width: 1000,
        height: 80,
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.3,
          outDuration: 0.2,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "caption-content",
        content: "Enter your subtitles or captions here",
        fontFamily: "Arial",
        fontSize: 30,
        fontWeight: 400,
        color: "#ffd43b",
        align: "center",
        x: 460,
        y: 935,
        width: 1000,
        height: 50,
        role: "primary",
        animation: {
          in: "typewriter",
          out: "fade",
          inDuration: 1.0,
          outDuration: 0.2,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "pill-callout",
    label: "Clean Pill Callout",
    category: "callout",
    duration: 3,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "pill-bg",
        shape: "circle",
        fill: "#ffd43b",
        x: 200,
        y: 200,
        width: 320,
        height: 80,
        animation: {
          in: "scale-in",
          out: "scale-out",
          inDuration: 0.4,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "callout-text",
        content: "LOOK HERE!",
        fontFamily: "Poppins",
        fontSize: 28,
        fontWeight: 400,
        color: "#000000",
        align: "center",
        x: 210,
        y: 215,
        width: 300,
        height: 50,
        role: "primary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "social-subscribe",
    label: "Youtube Subscribe Pill",
    category: "social",
    duration: 4,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "btn-bg",
        shape: "rect",
        fill: "#ff0000",
        x: 810,
        y: 900,
        width: 300,
        height: 70,
        animation: {
          in: "slide-up",
          out: "slide-down",
          inDuration: 0.4,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "sub-label",
        content: "SUBSCRIBE",
        fontFamily: "Poppins",
        fontSize: 28,
        fontWeight: 400,
        color: "#ffffff",
        align: "center",
        x: 820,
        y: 910,
        width: 280,
        height: 50,
        role: "primary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.2,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "countdown-timer",
    label: "Futuristic Countdown",
    category: "countdown",
    duration: 5,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "outer-ring",
        shape: "circle",
        fill: "rgba(124, 111, 255, 0.1)",
        stroke: { color: "#7c6fff", width: 4 },
        x: 810,
        y: 390,
        width: 300,
        height: 300,
        animation: {
          in: "scale-in",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.4,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "timer-digits",
        content: "5",
        fontFamily: "Poppins",
        fontSize: 120,
        fontWeight: 400,
        color: "#ffffff",
        align: "center",
        x: 820,
        y: 440,
        width: 280,
        height: 200,
        role: "primary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.3,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
];

export function getCanvasTemplatePreset(id: string): TextTemplate | undefined {
  return BUILTIN_CANVAS_TEMPLATES.find((t) => t.id === id);
}

export function getCanvasTemplatesByCategory(category: TemplateCategory): TextTemplate[] {
  return BUILTIN_CANVAS_TEMPLATES.filter((t) => t.category === category);
}
