allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@clypra/ui-color-picker@0.2.1'
  - '@clypra-studio/engine@1.4.0 || 1.5.0 || 1.6.0 || 1.7.0 || 1.8.0 || 1.8.1'
  - '@clypra-studio/native-render-wasm@0.2.0 || 0.3.0 || 0.3.1'
  - '@clypra-studio/runtime@0.2.3'
  - '@clypra-studio/shaders@0.2.0'
  - '@clypra-studio/types@0.6.0'
  - '@clypra-studio/ui@0.3.1'
