/**
 * motionPresets.ts — Production motion graphics presets modeled after
 * CapCut / TikTok / After Effects motion graphics templates.
 */

import type { MotionGraphicTemplate } from "../types";

export const VIRAL_COMIC_TEMPLATE: MotionGraphicTemplate = {
  id: "viral-comic-burst",
  name: "VIRAL! Comic Burst",
  description: "High-energy entrance with sweeping electric lightning and fire streaks, settling into a glowing comic burst card.",
  category: "Comic",
  resolution: { width: 1920, height: 1080 },
  fps: 60,
  phaseTiming: {
    introDuration: 0.6,
    holdDuration: 1.8,
    outroDuration: 0.6,
  },
  layers: [
    {
      id: "bg-aura",
      name: "Red Radiant Glow",
      type: "glow-aura",
      visible: true,
      locked: false,
      blendMode: "screen",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 0.7, rotation: 0, opacity: 0.85 },
      config: {
        color: "rgba(255, 10, 50, 0.9)",
        radius: 360,
        intensity: 0.85,
      },
    },
    {
      id: "comic-burst",
      name: "Comic Starburst Card",
      type: "vector-burst",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: -4, opacity: 1 },
      config: {
        points: 16,
        innerRadiusRatio: 0.55,
        fillColor: "#e60026",
        strokeColor: "#000000",
        strokeWidth: 8,
        jitter: 0.35,
        glowColor: "#ff1a40",
        glowRadius: 28,
        autoFitText: true,
        paddingX: 120,
        paddingY: 90,
      },
    },
    {
      id: "floating-stars",
      name: "Comic Pop Stars",
      type: "stars",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, opacity: 1 },
      config: {
        count: 8,
        minSize: 14,
        maxSize: 26,
        color: "#e60026",
        pulseSpeed: 4,
        spreadRadius: 360,
      },
    },
    {
      id: "fire-swoosh",
      name: "Entrance Fire Streaks",
      type: "fire-streaks",
      visible: true,
      locked: false,
      blendMode: "lighter",
      phaseScope: "intro-only",
      transform: { x: 0, y: 0, scaleX: 1.2, scaleY: 1, rotation: -8, opacity: 1 },
      config: {
        count: 4,
        primaryColor: "#ff3300",
        secondaryColor: "#ffcc00",
        intensity: 1.0,
        angle: -12,
      },
    },
    {
      id: "lightning-intro",
      name: "Electric Lightning Arcs",
      type: "lightning-arcs",
      visible: true,
      locked: false,
      blendMode: "lighter",
      phaseScope: "intro-only",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: -6, opacity: 1 },
      config: {
        count: 5,
        color: "#70d6ff",
        coreColor: "#ffffff",
        roughness: 0.45,
        branchChance: 0.35,
        glowRadius: 24,
        speed: 1.8,
        direction: "sweep-horizontal",
      },
    },
    {
      id: "primary-text",
      name: "Text Layer",
      type: "text",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: -5, opacity: 1 },
      config: {
        text: "VIRAL!",
        fontFamily: "Bangers",
        fontSize: 140,
        fontWeight: 900,
        fontStyle: "normal",
        fill: "#ffffff",
        strokeColor: "#000000",
        strokeWidth: 16,
        outerStrokeColor: "#ff0033",
        outerStrokeWidth: 12,
        glowColor: "#ff0033",
        glowRadius: 30,
        shadowColor: "rgba(0, 0, 0, 0.85)",
        shadowBlur: 16,
        shadowOffsetY: 8,
      },
    },
  ],
};

export const FIRE_FINAL_TEMPLATE: MotionGraphicTemplate = {
  id: "fire-final-wrap",
  name: "FINAL / LET'S GO Flame",
  description: "Aggressive flame wrap with heat dissipation and high-contrast volcanic typography.",
  category: "VFX",
  resolution: { width: 1920, height: 1080 },
  fps: 60,
  phaseTiming: {
    introDuration: 0.5,
    holdDuration: 2.0,
    outroDuration: 0.5,
  },
  layers: [
    {
      id: "fire-bg-aura",
      name: "Volcanic Aura",
      type: "glow-aura",
      visible: true,
      locked: false,
      blendMode: "screen",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1.2, scaleY: 0.6, rotation: 0, opacity: 0.8 },
      config: {
        color: "rgba(255, 68, 0, 0.85)",
        radius: 380,
        intensity: 0.9,
      },
    },
    {
      id: "fire-flames",
      name: "Flame Sweeps",
      type: "fire-streaks",
      visible: true,
      locked: false,
      blendMode: "lighter",
      phaseScope: "all",
      transform: { x: 0, y: 20, scaleX: 1, scaleY: 1, rotation: 0, opacity: 1 },
      config: {
        count: 6,
        primaryColor: "#ff4500",
        secondaryColor: "#ffd700",
        intensity: 0.95,
        angle: -5,
      },
    },
    {
      id: "fire-text",
      name: "Flame Text",
      type: "text",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, opacity: 1 },
      config: {
        text: "FINAL",
        fontFamily: "Anton",
        fontSize: 150,
        fontWeight: 900,
        fill: "#ffea00",
        strokeColor: "#1a0500",
        strokeWidth: 14,
        outerStrokeColor: "#ff3700",
        outerStrokeWidth: 10,
        glowColor: "#ff4d00",
        glowRadius: 36,
        shadowColor: "rgba(0, 0, 0, 0.9)",
        shadowBlur: 20,
        shadowOffsetY: 6,
      },
    },
  ],
};

export const CREATIVE_SPARKLE_TEMPLATE: MotionGraphicTemplate = {
  id: "creative-sparkle",
  name: "CREATIVE Luminous",
  description: "Ethereal particle dust, radiant white/gold glow, and modern cinematic typography.",
  category: "Trending",
  resolution: { width: 1920, height: 1080 },
  fps: 60,
  phaseTiming: {
    introDuration: 0.8,
    holdDuration: 1.6,
    outroDuration: 0.6,
  },
  layers: [
    {
      id: "creative-aura",
      name: "White Luminous Glow",
      type: "glow-aura",
      visible: true,
      locked: false,
      blendMode: "screen",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 0.5, rotation: 0, opacity: 0.9 },
      config: {
        color: "rgba(255, 255, 255, 0.75)",
        radius: 300,
        intensity: 0.7,
      },
    },
    {
      id: "creative-stars",
      name: "Sparkle Dust",
      type: "stars",
      visible: true,
      locked: false,
      blendMode: "lighter",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1.1, scaleY: 0.8, rotation: 0, opacity: 1 },
      config: {
        count: 14,
        minSize: 4,
        maxSize: 12,
        color: "#ffffff",
        pulseSpeed: 5,
        spreadRadius: 340,
      },
    },
    {
      id: "creative-text",
      name: "Creative Text",
      type: "text",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, opacity: 1 },
      config: {
        text: "CREATIVE",
        fontFamily: "Montserrat",
        fontSize: 120,
        fontWeight: 900,
        fill: "#ffffff",
        strokeColor: "#0d0d12",
        strokeWidth: 6,
        glowColor: "#ffffff",
        glowRadius: 28,
        shadowColor: "rgba(255, 255, 255, 0.5)",
        shadowBlur: 24,
        shadowOffsetY: 0,
      },
    },
  ],
};

export const TRENDY_NEON_TEMPLATE: MotionGraphicTemplate = {
  id: "trendy-neon-ring",
  name: "TRENDY Orbital Neon",
  description: "High-speed circular neon streaks wrapping around a bold condensed title.",
  category: "Neon",
  resolution: { width: 1920, height: 1080 },
  fps: 60,
  phaseTiming: {
    introDuration: 0.5,
    holdDuration: 2.0,
    outroDuration: 0.5,
  },
  layers: [
    {
      id: "trendy-aura",
      name: "Cyan & Red Aura",
      type: "glow-aura",
      visible: true,
      locked: false,
      blendMode: "screen",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 0.7, rotation: 0, opacity: 0.8 },
      config: {
        color: "rgba(0, 229, 255, 0.7)",
        radius: 320,
        intensity: 0.8,
      },
    },
    {
      id: "trendy-streaks",
      name: "Orbital Streaks",
      type: "fire-streaks",
      visible: true,
      locked: false,
      blendMode: "lighter",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 0.5, rotation: -20, opacity: 1 },
      config: {
        count: 4,
        primaryColor: "#00e5ff",
        secondaryColor: "#ff0055",
        intensity: 1.0,
        angle: -15,
      },
    },
    {
      id: "trendy-text",
      name: "Trendy Text",
      type: "text",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, opacity: 1 },
      config: {
        text: "TRENDY",
        fontFamily: "Outfit",
        fontSize: 130,
        fontWeight: 900,
        fill: "#ffffff",
        strokeColor: "#000000",
        strokeWidth: 10,
        outerStrokeColor: "#00e5ff",
        outerStrokeWidth: 8,
        glowColor: "#00e5ff",
        glowRadius: 32,
      },
    },
  ],
};

export const CLOUD_PUFFY_TEMPLATE: MotionGraphicTemplate = {
  id: "capcut-cloud-puffy",
  name: "CLOUD Puffy Pop",
  description: "CapCut iconic puffy cloud pop with per-character staggered drop bounce, ghost trails, outer white contour, and idle floating wave.",
  category: "Trending",
  resolution: { width: 1920, height: 1080 },
  fps: 60,
  phaseTiming: {
    introDuration: 0.6,
    holdDuration: 2.0,
    outroDuration: 0.5,
  },
  layers: [
    {
      id: "cloud-text-primary",
      name: "Cloud Typography",
      type: "text",
      visible: true,
      locked: false,
      blendMode: "source-over",
      phaseScope: "all",
      transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, opacity: 1 },
      config: {
        text: "CLOUD",
        fontFamily: '"Fredoka", "Lilita One", "Nunito", sans-serif',
        fontSize: 180,
        fontWeight: 900,
        tracking: 16,
        skewX: -0.13,
        condenseX: 0.95,
        fill: "#ffffff",
        strokeColor: "#000000",
        strokeWidth: 44,
        cloudOuterStrokeWidth: 22,
        cloudOuterStrokeColor: "#ffffff",
        fillCounters: true,
        perCharacter: true,
        staggerDelay: 0.07,
        entranceType: "drop-bounce",
        entranceDistance: 130,
        idleWave: true,
        idleWaveSpeed: 3.2,
        idleWaveAmplitude: 8,
        ghostTrail: false,
        cloudHalo: false,
        puffyBevel: false,
      },
    },
  ],
};

export const MOTION_PRESETS: MotionGraphicTemplate[] = [
  CLOUD_PUFFY_TEMPLATE,
  VIRAL_COMIC_TEMPLATE,
  FIRE_FINAL_TEMPLATE,
  CREATIVE_SPARKLE_TEMPLATE,
  TRENDY_NEON_TEMPLATE,
];
