import { TextEffectConfig, Preset } from "./types";

/** Style recipes (layer graphs): see `builtInRecipes` in src/engine/recipes.ts */

export const defaultConfig: TextEffectConfig = {
  text: "CLYPRA STUDIO",
  effectName: "My Effect",
  fontFamily: "Poppins",
  fontWeight: 700,
  fontStyle: "normal",
  fontSize: 80,
  letterSpacing: 4,
  lineHeight: 1.2,
  fillType: "solid",
  fillColor: "#FFFFFF",
  fillGradientAngle: 90,
  fillGradientStops: [
    { color: "#FFFFFF", offset: 0 },
    { color: "#E0E0E0", offset: 100 },
  ],
  strokeEnabled: false,
  strokeColor: "#7C6FFF",
  strokeWidth: 4,
  strokePosition: "outside",
  strokeOpacity: 100,
  strokeLineJoin: "round",
  glowLayers: [
    { enabled: false, color: "#7C6FFF", blur: 20, opacity: 80, type: "outer" },
    { enabled: false, color: "#FF007C", blur: 40, opacity: 60, type: "outer" },
    { enabled: false, color: "#00F0FF", blur: 60, opacity: 40, type: "outer" },
  ],
  shadowEnabled: false,
  shadowColor: "#000000",
  shadowBlur: 10,
  shadowOffsetX: 5,
  shadowOffsetY: 5,
  shadowOpacity: 80,
  shadowType: "drop",
  bevelEnabled: false,
  bevelDepth: 5,
  bevelHighlight: "#FFFFFF",
  bevelShadow: "#000000",
  bevelDirection: "bottom-right",
  bevelCoreColor: "#000000",
  bevelEdgeColor: "#2A2A38",
  bevelEdgeWidth: 0,
  bevelBlur: 0,
  bevelBlurColor: "#000000",
  bevelPerspectiveEnabled: false,
  bevelVanishingPointX: 40,
  bevelVanishingPointY: 80,
  bevelFocalLength: 400,
  stackEnabled: false,
  stackCount: 3,
  stackOffsetX: 10,
  stackOffsetY: -10,
  stackOpacityDecay: 20,
  stackColor1: "#FF7C00",
  stackColor2: "#00FFDD",
  stackColor3: "#FF00AA",
  stackColor4: "#AA00FF",
  panelEnabled: false,
  panelColor: "#1E1E26",
  panelOpacity: 80,
  panelRadius: 12,
  panelPaddingX: 40,
  panelPaddingY: 20,
  panelStrokeEnabled: false,
  panelStrokeColor: "#2A2A38",
  panelStrokeWidth: 2,
  canvasWidth: 800,
  canvasHeight: 200,
  textPosX: "center",
  textPosY: "middle",
  wrapText: true,
  autoFitText: false,

  // Ink Brush custom properties
  inkColor: "#FFFFFF",
  bristleDensity: 0.8,
  bristleSkipRate: 0.2,
  dripRate: 0.3,
  dripMaxLength: 40,
  grainDensity: 0.15,
  skewX: -0.2,
};

export const builtInPresets: Preset[] = [
  {
    id: "premium-sticker",
    name: "STICKER",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "StickerEffect",
      fontFamily: "Arial Rounded MT Bold",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 88,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FFCE00", offset: 0 },
        { color: "#E05300", offset: 100 },
      ],
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 15,
      strokePosition: "outside",
      strokeType: "single",
      strokeLineJoin: "round",
      strokeOpacity: 100,
      bevelEnabled: true,
      bevelDepth: 8,
      bevelDirection: "bottom-right",
      bevelHighlight: "#FFCE00",
      bevelCoreColor: "#4E1901",
      bevelShadow: "#1D0A00",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 14,
      shadowOffsetX: 6,
      shadowOffsetY: 8,
      shadowOpacity: 65,
      shadowType: "drop",
    },
  },

  {
    id: "premium-holo",
    name: "HOLOGRAPHIC",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "HolographicEffect",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 100,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 125,
      fillGradientStops: [
        { color: "#6FE3FF", offset: 0 },
        { color: "#D196FF", offset: 25 },
        { color: "#FF9CEE", offset: 50 },
        { color: "#FFE49E", offset: 75 },
        { color: "#D4FFF1", offset: 100 },
      ],
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeType: "single",
      strokeOpacity: 100,
      glowLayers: [{ enabled: true, color: "#D196FF", blur: 15, opacity: 50, type: "outer" }],
      bevelEnabled: true,
      bevelDepth: 4,
      bevelDirection: "bottom-right",
      bevelHighlight: "#FFFFFF",
      bevelCoreColor: "#2A3540",
      bevelShadow: "#0E151D",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 20,
      shadowOffsetX: 6,
      shadowOffsetY: 10,
      shadowOpacity: 90,
      shadowType: "drop",
    },
  },

  {
    id: "classic-ink",
    name: "Classic Ink",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "Classic Ink",
      effectName: "ClassicInk",
      fontFamily: "Playfair Display",
      fontWeight: 700,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 1,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FDFBF7", offset: 0 },
        { color: "#EAE5D9", offset: 100 },
      ],
      strokeEnabled: true,
      strokeColor: "#1E1E26",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#3D2B1F",
      shadowBlur: 14,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowOpacity: 90,
      shadowType: "drop",
    },
  },

  {
    id: "neon-crimson",
    name: "Neon Crimson",
    category: "Neon",
    config: {
      ...defaultConfig,
      text: "NEON",
      effectName: "NeonCrimson",
      fontFamily: "Bebas Neue",
      fontWeight: 700,
      fontStyle: "normal",
      fontSize: 100,
      letterSpacing: 6,
      lineHeight: 1.2,
      fillType: "none",
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 3,
      strokePosition: "center",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      glowLayers: [
        { enabled: true, color: "#FF003C", blur: 12, opacity: 100, type: "outer" },
        { enabled: true, color: "#FF003C", blur: 35, opacity: 80, type: "outer" },
        { enabled: true, color: "#FF003C", blur: 80, opacity: 60, type: "outer" },
      ],
      shadowEnabled: false,
    },
  },

  {
    id: "cyberpunk-yellow",
    name: "Cyberpunk Yellow",
    category: "Neon",
    config: {
      ...defaultConfig,
      text: "CYBER",
      effectName: "CyberpunkYellow",
      fontFamily: "Anton",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 90,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FFE600",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#FFE600",
      shadowBlur: 15,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      shadowOpacity: 95,
      shadowType: "drop",
    },
  },

  {
    id: "retro-comic",
    name: "Retro Comic",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "BOOM!",
      effectName: "RetroComic",
      fontFamily: "Arial Black",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 3,
      lineHeight: 1.1,
      fillType: "solid",
      fillColor: "#000000",
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 6,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      glowLayers: [
        { enabled: true, color: "#000000", blur: 0, opacity: 100, type: "outer", strength: 1, spread: 3 },
        { enabled: false, color: "#FF007C", blur: 40, opacity: 60, type: "outer" },
        { enabled: false, color: "#00F0FF", blur: 60, opacity: 40, type: "outer" },
      ],
      // panelEnabled: true,
      // panelColor: "#FFE100",
      // panelOpacity: 100,
      // panelRadius: 10,
      // panelPaddingX: 55,
      // panelPaddingY: 35,
      // panelStrokeEnabled: true,
      // panelStrokeColor: "#000000",
      // panelStrokeWidth: 4,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 0,
      shadowOffsetX: 8,
      shadowOffsetY: 8,
      shadowOpacity: 100,
      shadowType: "drop",
    },
  },
];
