import { TextEffectConfig, Preset } from "./types";

/** Style recipes (layer graphs): see `builtInRecipes` in src/engine/recipes.ts */

export const defaultConfig: TextEffectConfig = {
  text: "CLYPRA",
  effectName: "My Effect",
  fontFamily: "Poppins",
  fontWeight: 700,
  fontStyle: "normal",
  fontSize: 80,
  letterSpacing: 4,
  lineHeight: 1.2,
  fillType: "solid",
  fillColor: "#FFFFFF",
  fillGradientAngle: 90,
  fillGradientStops: [
    { color: "#FFFFFF", offset: 0 },
    { color: "#E0E0E0", offset: 100 }
  ],
  strokeEnabled: true,
  strokeColor: "#7C6FFF",
  strokeWidth: 4,
  strokePosition: "outside",
  strokeOpacity: 100,
  strokeLineJoin: "round",
  glowLayers: [
    { enabled: false, color: "#7C6FFF", blur: 20, opacity: 80, type: "outer" },
    { enabled: false, color: "#FF007C", blur: 40, opacity: 60, type: "outer" },
    { enabled: false, color: "#00F0FF", blur: 60, opacity: 40, type: "outer" }
  ],
  shadowEnabled: false,
  shadowColor: "#000000",
  shadowBlur: 10,
  shadowOffsetX: 5,
  shadowOffsetY: 5,
  shadowOpacity: 80,
  shadowType: "drop",
  bevelEnabled: false,
  bevelDepth: 5,
  bevelHighlight: "#FFFFFF",
  bevelShadow: "#000000",
  bevelDirection: "bottom-right",
  bevelCoreColor: "#000000",
  bevelEdgeColor: "#2A2A38",
  bevelEdgeWidth: 0,
  bevelBlur: 0,
  bevelBlurColor: "#000000",
  bevelPerspectiveEnabled: false,
  bevelVanishingPointX: 40,
  bevelVanishingPointY: 80,
  bevelFocalLength: 400,
  stackEnabled: false,
  stackCount: 3,
  stackOffsetX: 10,
  stackOffsetY: -10,
  stackOpacityDecay: 20,
  stackColor1: "#FF7C00",
  stackColor2: "#00FFDD",
  stackColor3: "#FF00AA",
  stackColor4: "#AA00FF",
  panelEnabled: false,
  panelColor: "#1E1E26",
  panelOpacity: 80,
  panelRadius: 12,
  panelPaddingX: 40,
  panelPaddingY: 20,
  panelStrokeEnabled: false,
  panelStrokeColor: "#2A2A38",
  panelStrokeWidth: 2,
  canvasWidth: 800,
  canvasHeight: 200,
  textPosX: "center",
  textPosY: "middle",
  wrapText: true,
  autoFitText: false,

  // Ink Brush custom properties
  inkColor: "#FFFFFF",
  bristleDensity: 0.8,
  bristleSkipRate: 0.20,
  dripRate: 0.30,
  dripMaxLength: 40,
  grainDensity: 0.15,
  skewX: -0.2,

  // Fire Engine custom properties
  fireColor: "#FF5500",
  fireIntensity: 5,
  fireFlameHeight: 80,
  fireEmberCount: 150,

  // Ice Engine custom properties
  iceColor: "#AADDFF",
  iceThickness: 6,
  iceIcicleHeight: 25,
  iceFrostDensity: 0.6,
  iceSnowHeight: 10,

  // Aura Engine custom properties
  auraColor: "#A855F7",
  auraGlowColor: "#6B21A8",
  auraIntensity: 6,
  auraReach: 35,
  auraParticleCount: 160
};

export const builtInPresets: Preset[] = [
  {
    id: "worms-eye-3d",
    name: "Worm's Eye 3D",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "Perspective3D",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 100,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FFFFFF",
      strokeEnabled: false,
      bevelEnabled: true,
      bevelDepth: 45,
      bevelHighlight: "#E2E8F0",
      bevelCoreColor: "#475569",
      bevelShadow: "#1E293B",
      bevelDirection: "bottom-right",
      bevelEdgeWidth: 0,
      bevelBlur: 0,
      bevelPerspectiveEnabled: true,
      bevelVanishingPointX: 40,
      bevelVanishingPointY: 80,
      bevelFocalLength: 350,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 20,
      shadowOffsetX: 40,
      shadowOffsetY: 40,
      shadowOpacity: 90,
      shadowType: "drop",
      panelEnabled: true,
      panelColor: "#0A0A0E",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 60,
      panelPaddingY: 45
    }
  },
  {
    id: "3d-block-extrusion",
    name: "3D Block Extrusion",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "3DBlock",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 100,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FFFFFF",
      strokeEnabled: false,
      bevelEnabled: true,
      bevelDepth: 35,
      bevelHighlight: "#CBD5E1",
      bevelCoreColor: "#475569",
      bevelShadow: "#1E293B",
      bevelDirection: "bottom-right",
      bevelEdgeWidth: 0,
      bevelBlur: 0,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 16,
      shadowOffsetX: 38,
      shadowOffsetY: 38,
      shadowOpacity: 85,
      shadowType: "drop",
      panelEnabled: true,
      panelColor: "#0D0D11",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 60,
      panelPaddingY: 40
    }
  },
  {
    id: "premium-sticker",
    name: "09. STICKER",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "StickerEffect",
      fontFamily: "Arial Rounded MT Bold",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 88,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FFCE00", offset: 0 },
        { color: "#E05300", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 15,
      strokePosition: "outside",
      strokeType: "single",
      strokeLineJoin: "round",
      strokeOpacity: 100,
      bevelEnabled: true,
      bevelDepth: 8,
      bevelDirection: "bottom-right",
      bevelHighlight: "#FFCE00",
      bevelCoreColor: "#4E1901",
      bevelShadow: "#1D0A00",
      panelEnabled: true,
      panelColor: "#050508",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 56,
      panelPaddingY: 42,
      panelStrokeEnabled: true,
      panelStrokeColor: "#171721",
      panelStrokeWidth: 1.5,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 14,
      shadowOffsetX: 6,
      shadowOffsetY: 8,
      shadowOpacity: 65,
      shadowType: "drop"
    }
  },
  {
    id: "premium-holo",
    name: "10. HOLOGRAPHIC",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "HolographicEffect",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 100,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 125,
      fillGradientStops: [
        { color: "#6FE3FF", offset: 0 },
        { color: "#D196FF", offset: 25 },
        { color: "#FF9CEE", offset: 50 },
        { color: "#FFE49E", offset: 75 },
        { color: "#D4FFF1", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeType: "single",
      strokeOpacity: 100,
      glowLayers: [
        { enabled: true, color: "#D196FF", blur: 15, opacity: 50, type: "outer" }
      ],
      bevelEnabled: true,
      bevelDepth: 4,
      bevelDirection: "bottom-right",
      bevelHighlight: "#FFFFFF",
      bevelCoreColor: "#2A3540",
      bevelShadow: "#0E151D",
      panelEnabled: true,
      panelColor: "#030406",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 56,
      panelPaddingY: 42,
      panelStrokeEnabled: true,
      panelStrokeColor: "#11151F",
      panelStrokeWidth: 1.5,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 20,
      shadowOffsetX: 6,
      shadowOffsetY: 10,
      shadowOpacity: 90,
      shadowType: "drop"
    }
  },
  {
    id: "ink-brush",
    name: "16. Ink Brush",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "InkBrush",
      customRenderer: "InkBrushEngine",
      fontFamily: "Bebas Neue",
      fontWeight: 900,
      fontStyle: "italic",
      fontSize: 96,
      letterSpacing: 2,
      lineHeight: 1.1,
      fillType: "solid",
      fillColor: "#FFFFFF",
      strokeEnabled: false,
      panelEnabled: true,
      panelColor: "#121216",
      panelOpacity: 100,
      panelRadius: 12,
      panelPaddingX: 55,
      panelPaddingY: 35,
      panelStrokeEnabled: true,
      panelStrokeColor: "#22222E",
      panelStrokeWidth: 1,
      // Custom ink controls
      inkColor: "#FFFFFF",
      bristleDensity: 0.8,
      bristleSkipRate: 0.20,
      dripRate: 0.30,
      dripMaxLength: 40,
      grainDensity: 0.15,
      skewX: -0.2
    }
  },
  {
    id: "realistic-fire",
    name: "18. Fire",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "FireEffect",
      customRenderer: "FireEngine",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 105,
      letterSpacing: 3,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FF5500",
      strokeEnabled: false,
      panelEnabled: true,
      panelColor: "#050100",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 56,
      panelPaddingY: 42,
      panelStrokeEnabled: true,
      panelStrokeColor: "#1A0E0A",
      panelStrokeWidth: 1.5,
      fireColor: "#FF5500",
      fireIntensity: 5.5,
      fireFlameHeight: 75,
      fireEmberCount: 160
    }
  },
  {
    id: "realistic-ice",
    name: "19. Ice",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "IceEffect",
      customRenderer: "IceEngine",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 105,
      letterSpacing: 3,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#AADDFF",
      strokeEnabled: false,
      panelEnabled: true,
      panelColor: "#020308",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 56,
      panelPaddingY: 42,
      panelStrokeEnabled: true,
      panelStrokeColor: "#111822",
      panelStrokeWidth: 1.5,
      iceColor: "#AADDFF",
      iceThickness: 6,
      iceIcicleHeight: 25,
      iceFrostDensity: 0.7,
      iceSnowHeight: 10
    }
  },
  {
    id: "realistic-aura",
    name: "20. Particle Aura",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "TEXT",
      effectName: "AuraEffect",
      customRenderer: "AuraEngine",
      fontFamily: "Impact",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 105,
      letterSpacing: 3,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#E8D5FF",
      strokeEnabled: false,
      panelEnabled: true,
      panelColor: "#05000A",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 56,
      panelPaddingY: 42,
      panelStrokeEnabled: true,
      panelStrokeColor: "#1B0F2E",
      panelStrokeWidth: 1.5,
      auraColor: "#C084FC",
      auraGlowColor: "#581C87",
      auraIntensity: 7.0,
      auraReach: 48,
      auraParticleCount: 220
    }
  },
  {
    id: "classic-ink",
    name: "Classic Ink",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "Classic Ink",
      effectName: "ClassicInk",
      fontFamily: "Playfair Display",
      fontWeight: 700,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 1,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FDFBF7", offset: 0 },
        { color: "#EAE5D9", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#1E1E26",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#3D2B1F",
      shadowBlur: 14,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowOpacity: 90,
      shadowType: "drop"
    }
  },
  {
    id: "neon-crimson",
    name: "Neon Crimson",
    category: "Neon",
    config: {
      ...defaultConfig,
      text: "NEON",
      effectName: "NeonCrimson",
      fontFamily: "Bebas Neue",
      fontWeight: 700,
      fontStyle: "normal",
      fontSize: 100,
      letterSpacing: 6,
      lineHeight: 1.2,
      fillType: "none",
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 3,
      strokePosition: "center",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      glowLayers: [
        { enabled: true, color: "#FF003C", blur: 12, opacity: 100, type: "outer" },
        { enabled: true, color: "#FF003C", blur: 35, opacity: 80, type: "outer" },
        { enabled: true, color: "#FF003C", blur: 80, opacity: 60, type: "outer" }
      ],
      shadowEnabled: false
    }
  },
  {
    id: "molten-gold",
    name: "Molten Gold",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "GOLDEN",
      effectName: "MoltenGold",
      fontFamily: "Montserrat",
      fontWeight: 800,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FFE259", offset: 0 },
        { color: "#FFA751", offset: 50 },
        { color: "#8B5A00", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#4A2E00",
      strokeWidth: 3,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      bevelEnabled: true,
      bevelDepth: 8,
      bevelHighlight: "#FFFFFF",
      bevelShadow: "#251200",
      bevelDirection: "bottom-right",
      shadowEnabled: true,
      shadowColor: "#0D0700",
      shadowBlur: 12,
      shadowOffsetX: 4,
      shadowOffsetY: 6,
      shadowOpacity: 85
    }
  },
  {
    id: "cyberpunk-yellow",
    name: "Cyberpunk Yellow",
    category: "Neon",
    config: {
      ...defaultConfig,
      text: "CYBER",
      effectName: "CyberpunkYellow",
      fontFamily: "Anton",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 90,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FFE600",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 6,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#FFE600",
      shadowBlur: 15,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      shadowOpacity: 95,
      shadowType: "drop"
    }
  },
  {
    id: "glitch-corrupt",
    name: "Glitch Corrupt",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "SYSTEM ERR",
      effectName: "GlitchCorrupt",
      fontFamily: "Press Start 2P",
      fontWeight: 400,
      fontStyle: "normal",
      fontSize: 42,
      letterSpacing: 2,
      lineHeight: 1.3,
      fillType: "solid",
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#111115",
      strokeWidth: 4,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "miter"
    }
  },
  {
    id: "frosted-mint",
    name: "Frosted Mint",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "FROSTED",
      effectName: "FrostedMint",
      fontFamily: "Raleway",
      fontWeight: 600,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 6,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 45,
      fillGradientStops: [
        { color: "#E0F7FA", offset: 0 },
        { color: "#80CBC4", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#2E5B55",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeOpacity: 70,
      strokeLineJoin: "round",
      glowLayers: [
        { enabled: true, color: "#B2DFDB", blur: 25, opacity: 70, type: "outer" }
      ],
      shadowEnabled: true,
      shadowColor: "#004D40",
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      shadowOpacity: 45
    }
  },
  {
    id: "deep-ocean",
    name: "Deep Ocean",
    category: "Neon",
    config: {
      ...defaultConfig,
      text: "ABYSS",
      effectName: "DeepOcean",
      fontFamily: "Nunito",
      fontWeight: 800,
      fontStyle: "normal",
      fontSize: 90,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 135,
      fillGradientStops: [
        { color: "#00F2FE", offset: 0 },
        { color: "#4FACFE", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#001D3D",
      strokeWidth: 5,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      glowLayers: [
        { enabled: true, color: "#00F2FE", blur: 20, opacity: 60, type: "outer" }
      ]
    }
  },
  {
    id: "studio-broadcast",
    name: "Studio Broadcast",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "ON AIR",
      effectName: "StudioBroadcast",
      fontFamily: "Montserrat",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 80,
      letterSpacing: 18,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FFFFFF",
      strokeEnabled: false,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 35,
      shadowOffsetX: 0,
      shadowOffsetY: 15,
      shadowOpacity: 60,
      shadowType: "drop"
    }
  },
  {
    id: "retro-comic",
    name: "Retro Comic",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "BOOM!",
      effectName: "RetroComic",
      fontFamily: "Arial Black",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 3,
      lineHeight: 1.1,
      fillType: "solid",
      fillColor: "#000000",
      strokeEnabled: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 6,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      glowLayers: [
        { enabled: true, color: "#000000", blur: 0, opacity: 100, type: "outer", strength: 1, spread: 3 },
        { enabled: false, color: "#FF007C", blur: 40, opacity: 60, type: "outer" },
        { enabled: false, color: "#00F0FF", blur: 60, opacity: 40, type: "outer" }
      ],
      panelEnabled: true,
      panelColor: "#FFE100",
      panelOpacity: 100,
      panelRadius: 10,
      panelPaddingX: 55,
      panelPaddingY: 35,
      panelStrokeEnabled: true,
      panelStrokeColor: "#000000",
      panelStrokeWidth: 4,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 0,
      shadowOffsetX: 8,
      shadowOffsetY: 8,
      shadowOpacity: 100,
      shadowType: "drop"
    }
  },
  {
    id: "ink-spill",
    name: "Ink Spill & Spray",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "INK",
      effectName: "InkSpill",
      fontFamily: "Permanent Marker",
      fontWeight: 900,
      fontStyle: "italic",
      fontSize: 85,
      letterSpacing: 4,
      lineHeight: 1.1,
      fillType: "solid",
      fillColor: "#FFFFFF",
      strokeEnabled: false,
      glowLayers: [
        { enabled: true, color: "#000000", blur: 15, opacity: 80, type: "outer", strength: 1, spread: 2 }
      ],
      panelEnabled: true,
      panelColor: "#121216",
      panelOpacity: 100,
      panelRadius: 12,
      panelPaddingX: 55,
      panelPaddingY: 35,
      panelStrokeEnabled: true,
      panelStrokeColor: "#22222E",
      panelStrokeWidth: 1,
      shadowEnabled: false,
      shadowColor: "#000000",
      shadowBlur: 10,
      shadowOffsetX: 0,
      shadowOffsetY: 5,
      shadowOpacity: 50,
      shadowType: "drop"
    }
  },
  {
    id: "luxury-double",
    name: "Double Outline Badge",
    category: "Classic",
    config: {
      ...defaultConfig,
      text: "STROKE",
      effectName: "LuxuryDouble",
      fontFamily: "Space Grotesk",
      fontWeight: 800,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "linear",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FFFFFF", offset: 0 },
        { color: "#E5E7EB", offset: 45 },
        { color: "#9CA3AF", offset: 55 },
        { color: "#D1D5DB", offset: 100 }
      ],
      strokeEnabled: true,
      strokeColor: "#0F172A",
      strokeWidth: 3,
      strokeType: "double",
      strokeColorSecondary: "#F8FAFC",
      strokeWidthSecondary: 5,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "miter",
      bevelEnabled: true,
      bevelDepth: 4,
      bevelHighlight: "#FFFFFF",
      bevelShadow: "#0F172A",
      bevelDirection: "bottom-right",
      bevelCoreColor: "#1E293B",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 15,
      shadowOffsetX: 6,
      shadowOffsetY: 8,
      shadowOpacity: 75
    }
  },
  {
    id: "chalk-sketch",
    name: "Classic Chalk Sketch",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "CHALK",
      effectName: "ChalkDust",
      fontFamily: "Space Grotesk",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 90,
      letterSpacing: 6,
      lineHeight: 1.2,
      fillType: "pattern",
      fillColor: "#E2E8F0",
      patternType: "chalk",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeOpacity: 60,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 8,
      shadowOffsetX: 3,
      shadowOffsetY: 4,
      shadowOpacity: 50,
      bevelEnabled: false,
      panelEnabled: true,
      panelColor: "#111115",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 45,
      panelPaddingY: 25,
      panelStrokeEnabled: true,
      panelStrokeColor: "#1E293B",
      panelStrokeWidth: 1
    }
  },
  {
    id: "vintage-film",
    name: "Vintage Analog Film",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "FILM",
      effectName: "AnalogFilm",
      fontFamily: "Space Grotesk",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "pattern",
      fillColor: "#E2E8F0",
      patternType: "film",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      strokePosition: "outside",
      strokeOpacity: 60,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 10,
      shadowOffsetX: 4,
      shadowOffsetY: 6,
      shadowOpacity: 65,
      bevelEnabled: false,
      panelEnabled: true,
      panelColor: "#111115",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 45,
      panelPaddingY: 25,
      panelStrokeEnabled: true,
      panelStrokeColor: "#1E293B",
      panelStrokeWidth: 1
    }
  },
  {
    id: "brushed-steel",
    name: "Brushed Steel Alloy",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "STEEL",
      effectName: "BrushedAlloy",
      fontFamily: "JetBrains Mono",
      fontWeight: 800,
      fontStyle: "normal",
      fontSize: 80,
      letterSpacing: 2,
      lineHeight: 1.2,
      fillType: "pattern",
      fillColor: "#CBD5E1",
      patternType: "brushed",
      strokeEnabled: true,
      strokeColor: "#334155",
      strokeWidth: 3,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 12,
      shadowOffsetX: 5,
      shadowOffsetY: 8,
      shadowOpacity: 80,
      bevelEnabled: true,
      bevelDepth: 3,
      bevelHighlight: "#FFFFFF",
      bevelShadow: "#1E293B",
      bevelDirection: "bottom-right",
      panelEnabled: true,
      panelColor: "#0B0F19",
      panelOpacity: 100,
      panelRadius: 12,
      panelPaddingX: 45,
      panelPaddingY: 25,
      panelStrokeEnabled: true,
      panelStrokeColor: "#1E293B",
      panelStrokeWidth: 1
    }
  },
  {
    id: "ancient-marble",
    name: "Golden Empress Marble",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "MARBLE",
      effectName: "EmpressMarble",
      fontFamily: "Space Grotesk",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 80,
      letterSpacing: 5,
      lineHeight: 1.2,
      fillType: "pattern",
      fillColor: "#F5F5F4",
      patternType: "marble",
      strokeEnabled: true,
      strokeColor: "#1C1917",
      strokeWidth: 4,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "miter",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 16,
      shadowOffsetX: 6,
      shadowOffsetY: 10,
      shadowOpacity: 75,
      bevelEnabled: true,
      bevelDepth: 4,
      bevelHighlight: "#FFFFFF",
      bevelShadow: "#27272A",
      bevelDirection: "bottom-right",
      panelEnabled: true,
      panelColor: "#1C1917",
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 45,
      panelPaddingY: 25,
      panelStrokeEnabled: true,
      panelStrokeColor: "#292524",
      panelStrokeWidth: 1
    }
  },
  {
    id: "pop-art-halftone",
    name: "Retro Halftone Screen",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "RETRO",
      effectName: "ComicHalftone",
      fontFamily: "Space Grotesk",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 3,
      lineHeight: 1.2,
      fillType: "pattern",
      fillColor: "#FACC15",
      patternType: "halftone",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 0,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowOpacity: 100,
      panelEnabled: true,
      panelColor: "#FFFFFF",
      panelOpacity: 100,
      panelRadius: 12,
      panelPaddingX: 45,
      panelPaddingY: 25,
      panelStrokeEnabled: true,
      panelStrokeColor: "#000000",
      panelStrokeWidth: 3
    }
  },
  {
    id: "vintage-paper",
    name: "Vintage Crumpled Paper",
    category: "Experimental",
    config: {
      ...defaultConfig,
      text: "CRAFT",
      effectName: "CrumpledPaper",
      fontFamily: "Space Grotesk",
      fontWeight: 900,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 4,
      lineHeight: 1.2,
      fillType: "pattern",
      fillColor: "#F5F2EB", // warm rustic paper fiber
      patternType: "paper",
      strokeEnabled: true,
      strokeColor: "#473E2C",
      strokeWidth: 3,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 14,
      shadowOffsetX: 4,
      shadowOffsetY: 8,
      shadowOpacity: 60,
      bevelEnabled: false,
      panelEnabled: true,
      panelColor: "#1E1A11", // rustic warm graphite panel
      panelOpacity: 100,
      panelRadius: 16,
      panelPaddingX: 45,
      panelPaddingY: 25,
      panelStrokeEnabled: true,
      panelStrokeColor: "#332B1C",
      panelStrokeWidth: 1
    }
  }
];
