import { Type } from "@google/genai";

export const textEffectConfigSchemaProperties = {
  effectName: { type: Type.STRING, description: "Descriptive artistic name of the style" },
  fontFamily: {
    type: Type.STRING,
    description:
      "Web font like 'Inter', 'Impact', 'Georgia', 'Arial Black', 'Poppins', 'Bebas Neue'",
  },
  fontWeight: { type: Type.INTEGER, description: "400 to 900" },
  fontStyle: { type: Type.STRING, description: "'normal' or 'italic'" },
  fontSize: { type: Type.INTEGER, description: "40 to 120" },
  letterSpacing: { type: Type.INTEGER, description: "-5 to 20" },
  lineHeight: { type: Type.NUMBER, description: "0.8 to 2.0" },
  fillType: { type: Type.STRING, description: "'solid', 'linear', 'radial', 'pattern', or 'none'" },
  fillColor: { type: Type.STRING },
  fillGradientAngle: { type: Type.INTEGER, description: "0 to 360" },
  fillGradientStops: {
    type: Type.ARRAY,
    items: {
      type: Type.OBJECT,
      properties: {
        color: { type: Type.STRING },
        offset: { type: Type.INTEGER, description: "0 to 100" },
      },
      required: ["color", "offset"],
    },
  },
  patternType: {
    type: Type.STRING,
    description: "chalk, noise, grunge, carbon, stripes, film, brushed, marble, halftone, paper",
  },
  strokeEnabled: { type: Type.BOOLEAN },
  strokeColor: { type: Type.STRING },
  strokeWidth: { type: Type.INTEGER, description: "0 to 20" },
  strokePosition: { type: Type.STRING, description: "'outside', 'center', or 'inside'" },
  strokeOpacity: { type: Type.INTEGER, description: "0 to 100" },
  strokeLineJoin: { type: Type.STRING, description: "'round', 'miter', or 'bevel'" },
  glowLayers: {
    type: Type.ARRAY,
    items: {
      type: Type.OBJECT,
      properties: {
        enabled: { type: Type.BOOLEAN },
        color: { type: Type.STRING },
        blur: { type: Type.INTEGER, description: "0 to 150" },
        opacity: { type: Type.INTEGER, description: "0 to 100" },
        type: { type: Type.STRING, description: "'outer' or 'inner'" },
      },
      required: ["enabled", "color", "blur", "opacity", "type"],
    },
  },
  shadowEnabled: { type: Type.BOOLEAN },
  shadowColor: { type: Type.STRING },
  shadowBlur: { type: Type.INTEGER, description: "0 to 60" },
  shadowOffsetX: { type: Type.INTEGER, description: "-50 to 50" },
  shadowOffsetY: { type: Type.INTEGER, description: "-50 to 50" },
  shadowOpacity: { type: Type.INTEGER, description: "0 to 100" },
  shadowType: { type: Type.STRING, description: "'drop' or 'inner'" },
  bevelEnabled: { type: Type.BOOLEAN },
  bevelDepth: { type: Type.INTEGER, description: "0 to 15" },
  bevelHighlight: { type: Type.STRING },
  bevelShadow: { type: Type.STRING },
  bevelDirection: { type: Type.STRING, description: "'bottom-right', 'bottom', or 'right'" },
  panelEnabled: { type: Type.BOOLEAN },
  panelColor: { type: Type.STRING },
  panelOpacity: { type: Type.INTEGER, description: "0 to 100" },
  panelRadius: { type: Type.INTEGER, description: "0 to 45" },
  panelPaddingX: { type: Type.INTEGER, description: "0 to 60" },
  panelPaddingY: { type: Type.INTEGER, description: "0 to 30" },
  panelStrokeEnabled: { type: Type.BOOLEAN },
  panelStrokeColor: { type: Type.STRING },
  panelStrokeWidth: { type: Type.INTEGER, description: "1 to 8" },
};

export const textEffectConfigRequired = [
  "effectName",
  "fontFamily",
  "fontWeight",
  "fontStyle",
  "fontSize",
  "letterSpacing",
  "lineHeight",
  "fillType",
  "fillColor",
  "fillGradientAngle",
  "fillGradientStops",
  "strokeEnabled",
  "strokeColor",
  "strokeWidth",
  "strokePosition",
  "strokeOpacity",
  "strokeLineJoin",
  "glowLayers",
  "shadowEnabled",
  "shadowColor",
  "shadowBlur",
  "shadowOffsetX",
  "shadowOffsetY",
  "shadowOpacity",
  "shadowType",
  "bevelEnabled",
  "bevelDepth",
  "bevelHighlight",
  "bevelShadow",
  "bevelDirection",
  "panelEnabled",
  "panelColor",
  "panelOpacity",
  "panelRadius",
  "panelPaddingX",
  "panelPaddingY",
  "panelStrokeEnabled",
];

export const textEffectConfigResponseSchema = {
  type: Type.OBJECT,
  properties: textEffectConfigSchemaProperties,
  required: textEffectConfigRequired,
};

export const deepResearchResponseSchema = {
  type: Type.OBJECT,
  properties: {
    themeName: { type: Type.STRING },
    historicalContext: { type: Type.STRING },
    visualRules: { type: Type.ARRAY, items: { type: Type.STRING } },
    paletteDeconstruction: { type: Type.ARRAY, items: { type: Type.STRING } },
    config: {
      type: Type.OBJECT,
      properties: textEffectConfigSchemaProperties,
      required: textEffectConfigRequired,
    },
    extensionCode: { type: Type.STRING },
  },
  required: [
    "themeName",
    "historicalContext",
    "visualRules",
    "paletteDeconstruction",
    "config",
    "extensionCode",
  ],
};
